### ISSUE TITLE
Test loading users, workflows, roles and actions

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1536]
Using https://github.com/inveniosoftware/invenio-migrator test the dumping and loading of:
- [x] Users
- [x] Roles, actions (https://github.com/inveniosoftware/invenio-migrator/pull/41)
- [x] Remote accounts
- [x] Workflow objects (https://github.com/inspirehep/inspire-next/pull/1435)
- [x] Workflow audit logs (https://github.com/inspirehep/inspire-next/pull/1435)

**Comment by kaplun** [comment]
@jmartinm you are working on it right?

**Comment by jmartinm** [comment]
yep, me and @Panos512 It is almost ready.
