### ISSUE TITLE
Withdrawn papers

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1548]
Withdrawn papers must:
* [ ] be tagged with `"withdrawn": true` in JSON
* [ ] not be listed in author profile or in any citesummary
* [ ] however be matchable when resolving references
* [ ] however be searchable in literature
* [ ] clearly marked as withdrawn when displaying it

cc: @inspirehep/inspire-content

**Comment by michamos** [comment]
When a record gets flagged as withdrawn, the following should happen automatically (from @annetteholtkamp  in the recent thread on INSPIRE-DATA):

>The rules we agreed on I think are:

>Remove everything except the bare metadata so that these papers don’t show
unnecessarily up in searches. So keep only:
>- title (I usually put “Withdrawn:” in front to make it more visible)
>- authors (not their affiliations)
>- arXiv note and abstract
>- arXiv nr and rep nrs
>Remove everything else
>Add 980:Withdrawn

The title modification can be avoided if withdrawn records are displayed differently.

Unwithdrawing the record should revert to the latest non-withdrawn revision in order to restore all metadata including enhancements.

**Comment by ksachs** [comment]
keep also
- DOI 
- pubnote (773)
- hidden notes ?

What do we do with dates, pagenumbers, subject, pacs, license, hidden notes, attached files, ...?
I would delete the abstract(s) too.

Would it be better to define what should be deleted:

- affiliations
- keywords
- subject?
- pacs?
- references

**Comment by michamos** [comment]
@ksachs If it is withdrawn from arXiv but there is a non-withdrawn published version, should the record really be withdrawn?

**Comment by ksachs** [comment]
Even a journal article can be withdrawn:
https://inspirehep.net/record/1486153?ln=en
https://inspirehep.net/record/1377762?ln=en

**Comment by ksachs** [comment]
whether or not
https://inspirehep.net/record/1489216?ln=en
should be flagged as withdrawn is another (content) question

**Comment by michamos** [comment]
You are right, I was thinking about withdrawn on arXiv, not about retracted published papers (that should be handled consistently).

**Comment by aw-bib** [comment]
> Even a journal article can be withdrawn

Note that there are some problematic corner cases. E.g. some publishers mark articles as `withdrawn` if _they_ actually made a mistake (e.g. published the article twice, registered two DOIs). I understood, that the publishers have "no other means to handle this".

So, in the interest of the authors some sort of manual check might be in order.
