### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#1577]
* [ ] Ensure restricted records are not accessible #1288
* [ ] Ensure restricted collections are not accessible
* [ ] Ensure holding pen is accessible to cataloguer only
* [ ] Ensure admin interface is accessible to superadmins only
* [ ] Ensure POST/PUT/DELETE APIs are not available
* [ ] Ensure deleted records are not accessible #1541

**Comment by kaplun** [comment]
@jmartinm can you help coordinating this part? You are aware of status of collections/records. @spirosdelviniotis is taking care of deleted records in #1541

**Comment by jmartinm** [comment]
Closed by https://github.com/inspirehep/inspire-next/pull/1589

We just need to make sure to assign the correct roles and actions when we deploy Invenio 3.
