### ISSUE TITLE
Missing things in relations

### ISSUE THREAD

**Issue by tomaszgy** [inspirehep/inspire-next#1652]
Posting here few more things that in my opinion might/should be improved inside relations module.

**TODOs:**

- [ ] use links stored in `thesis` and `thesis_supervisor` fields in literature as an extra relation
- [ ] implement `get_citation_summary` for experiments in API (for now it seems unclear what is the connection between experiments and their papers)
- [ ] output data in CSV format in API (for now it is JSON) - especially important for impact graph and citation summary
- [ ] once https://github.com/inspirehep/inspire-next/pull/1612 is merged, replace line:
```python
index = InspireRecordIdProvider.schema_to_pid_type(record['$schema'])
```
in `migrate.py` with proper util function
- [ ]  create `get_earliest_date` util function and use it in `inspirehep/dojson/hep/receivers.py` and `inspirehep/modules/relations/builders/literature/builder.py`
- [ ] import properly `elements/country_code.json` schema element from inspire-schemas in `inspire hep/modules/relations/model/constants.py`
- [ ] once missing data are added to Demo records (as mentioned in https://github.com/inspirehep/inspire-next/issues/1648), update integration tests  by removing `x-fail` marks

As I won't be able to work on that, please feel free to pick things from the list. Thanks! 😄
