### ISSUE TITLE
tests: unit tests for workflows/tasks

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#1773]
Just spotted that there's an opportunity to gain ~2% coverage by adding **unit tests** to the workflows tasks. Moreover, I already found [a bug](https://travis-ci.org/inspirehep/inspire-next/jobs/176430251#L1520) and some code/tests that could be refactored.

- [x] Test `workflows/tasks/actions.py` (#1748)
- [x] Test `workflows/tasks/arxiv.py` (#2307)
- [x] Test `workflows/tasks/beard.py` (#1311)
- [ ] Test `workflows/tasks/classifier.py`
- [x] Test `workflows/tasks/magpie.py` (#1309)
- [ ] Test `workflows/tasks/matching.py`
- [x] Test `workflows/tasks/refextract.py` (several PRs)
- [x] Test `workflows/tasks/submission.py` ~ (#2313)
- [x] Test `workflows/tasks/upload.py` (#2315)

**Comment by jacquerie** [comment]
Essentially done, will be completed on case-by-case basis.
