### ISSUE TITLE
output formats porting

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#267]
Current INSPIRE formats (used in http://inspirehep.net) live in https://github.com/inspirehep/inspire/tree/master/bibformat/output_formats.

This task keeps track of the porting status:

* [ ] ~~HCA.bfo - Seems to be a hack for the reference correction form - http://inspirehep.net/record/1302452/export/hrf - this form will be reimplemented.~~
* [x] HCV.bfo - @ioannistsanaktsidis 
* [x] HLXE.bfo To be ported @ioannistsanaktsidis 
* [ ] HLXH.bfo Harvmarc format (I think it comes from [here](http://guides.is.uwa.edu.au/harvard)) should be checked if it is still up to date and port.
* [x] HLXU.bfo To be ported @ioannistsanaktsidis 
* [ ] ~~HRA.bfo - Reference correction workflow - Needs to be reimplemented~~
* [ ] ~~HRF.bfo - Reference correction workflow - Needs to be reimplemented~~
* [ ] ~~HRN.bfo - Reference correction workflow - Needs to be reimplemented~~
* [ ] ~~HRU.bfo - Reference correction workflow - Needs to be reimplemented~~
* [x] HTCV.bfo	- CV format (text) - To be ported @ioannistsanaktsidis
* [x] HX.bfo - BibTex @ioannistsanaktsidis 
* [ ] HXA.bfo - Same as BibTex but including abstract - Not sure it is needed.
* [x] TLCV.bfo - LaTeX(CV) - To be ported @ioannistsanaktsidis 
* [ ] XD.bfo - Dublin Core - Uses XSLT at the moment - To be ported
* [ ] XN.bfo - NLM format - Uses XSLT at the moment - To be ported
* [ ] XSTI.bfo - OSTI format - To be ported

An example of how the new formats look like (using `yml` instead of `bfo`) can be [seen here ](https://github.com/inspirehep/inspire-next/blob/master/inspire/base/output_formats/hb.yml)

**Comment by jmartinm** [comment]
![agiiicfc](https://cloud.githubusercontent.com/assets/580727/9192444/7698c8b4-400b-11e5-82a1-061e65095be9.png)


For reference, this is the usage of the different formats for the month of November 2014.

**Comment by jmartinm** [comment]
Brief and detailed records are here https://github.com/inspirehep/inspire-next/issues/297

**Comment by kaplun** [comment]
I assume detailed is under represented?

**Comment by jmartinm** [comment]
You mean that the number in the graph does not reflect reality for detailed?

One thing that would make the `brief` format so 'popular' is that every single search has 25 brief formats so obviously the number is meant to be very high

**Comment by kaplun** [comment]
Right, but I guess it was computed by grepping through of=HD in search results? I mean this number does not reflect when someone simply accessed /record/123, does it?

**Comment by jmartinm** [comment]
Yes, to be honest, I am not sure how brief and detailed were counted. We should ask @espacial for details

**Comment by espacial** [comment]
As @kaplun says, it is counted using of=HD. 

It is neither counting if people is accessing the detailed record, nor recounting 25 times the same search. As a small deviation, It would count two times the same query if you moved to the second page of the search results, though.

Conclusion: Yes, the detailed format is rarely used.

**Comment by kaplun** [comment]
Thanks for confirmation.

> Conclusion: Yes, the detailed format is rarely used.

... when displaying search results, but we don't know yet how this compare to when users directly access /record/123 which uses as well the detailed format. But, anyway, for this very context it doesn't really matter, with your explanation we know that (beside HD) the rest of the priorities seems quite reasonable.

**Comment by tsgit** [comment]
I think it make sense from inspire's default behavior that HD is most frequently accessed from clicks on links in search results, i.e. via /record/<recid> links in the brief result display and rarely via ?of=HD

also if these stats are solely based on ?of=<x> then links from detailed format like
http://inspirehep.net/record/811388/export/hx
are not counted, thus all formats offered there via ..../export/<x>  are undercounted

**Comment by kaplun** [comment]
Removing milestone since the missing formats are not a blocker for Enabling search.

**Comment by kaplun** [comment]
Separate issues now exists.
