### ISSUE TITLE
Design improvements for HEP brief search results

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#328]
The following changes need to be done for HEP record search results:

* [ ] Add number and checkbox in front of every result ?
* [x] When pressing Cite
    * [x] Change wording - Export Article -> Cite Article
    * [x] Add a bit more space after `Cite Article` title
    * [x] Make Download work
* [x] Make MathJax work in search results through CDN - see https://github.com/inspirehep/inspire-next/issues/283
* [ ] PDF Download - single button when only one available and dropdown menu when different versions available.
* [x] Add arXiv category close to the arxiv eprint number
* [x] In some cases, report numbers are useful to recognize the type of material. We need rules of what is the minimum info we have to display in brief results regarding report numbers.
* [x] Add `Published in` close to the publication note.
* [x] Explore whether it is useful to show the full DOI as it takes quite a lot of space. We might want to just the display the word DOI with a link to the DOI source.
* [x] Add year in all brief search results.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  for the last one, what it will be written in the dropdown. eg.Now the button says only PDF. In the dropdown we will have it like Version 1, Version 2?

**Comment by aw-bib** [comment]
If you add a checkbox to select articles on a page this is surely meant to do something with them. Thus  please consider a some way of selecting all in one go. We miss this dearly in 1.x...

**Comment by kaplun** [comment]
>  PDF Download - single button when only one available and dropdown menu when different versions available.

Actually this is a good question. So far we basically have always a .PDF and

**Comment by kaplun** [comment]
> PDF Download - single button when only one available and dropdown menu when different versions available.

This would actually require some more thoughts indeed: 
* if we are talking about publications, we typically will have only one PDF (from arXiv or from some SCOAP3 partner). Other revisions are going to be available to our users directly in arXiv.org. 
* On the other hand we might have plots extracted from the given paper and we have to think of a way to make this plots downloadable. But this can be solved later.
* For non HEP records, e.g. Data, then it's even more complex... to be further thought :-)

**Comment by annetteholtkamp** [comment]
It's not so unusual to have a non-arxiv preprint - e.g. a conf paper from CDS - and a published version.

- Annette


On 29 Oct 2015, at 21:45, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


PDF Download - single button when only one available and dropdown menu when different versions available.

This would actually require some more thoughts indeed:

  *   if we are talking about publications, we typically will have only one PDF (from arXiv or from some SCOAP3 partner). Other revisions are going to be available to our users directly in arXiv.org<http://arXiv.org>.
  *   On the other hand we might have plots extracted from the given paper and we have to think of a way to make this plots downloadable. But this can be solved later.
  *   For non HEP records, e.g. Data, then it's even more complex... to be further thought :-)

**Comment by jmartinm** [comment]
> It's not so unusual to have a non-arxiv preprint - e.g. a conf paper from CDS - and a published version.

@annetteholtkamp 

Do we have enough information in our metadata to show a description about the fulltext? Or we just have  a link to it?

Can you point to some examples in inspirehep with several fulltext so that we can test?

**Comment by jmartinm** [comment]
Updated with some more points. @nikpap Check if there is something missing that we have to add.

@annetteholtkamp Do we have some examples regarding multiple fulltext?

**Comment by annetteholtkamp** [comment]
Here’s one example: https://inspirehep.net/record/630171
Original full text from CERN Courier + reprint.

- Annette

**Comment by ioannistsanaktsidis** [comment]
Add number and checkbox in front of every result ? for the checkbox we already have it, are we going to need the number in the end?

**Comment by salmele** [comment]
Interesting one! Sometimes @annetteholtkamp gets feedback tickets where users say that record no.37 has to be changed (without sending the search, so usually this is quite useless). 

Do we have a reason (apart from the fact we have numbers now) for adding them?

I'd vote to go without and adding them if we hear (loud) disappointment for them being missed.

**Comment by bing13** [comment]
They may also help users when they’re paging through result pages.   If we have checkboxes so users can select sets of result items *across* search result pages, that perhaps might reduce this type of usage.

**Comment by annetteholtkamp** [comment]
Personally, I find them useful. Gives me some orientation if I have to check a list of records. Would be great if one could switch the numbering on.

- Annette

On 02 Dec 2015, at 18:57, Bernard Hecker <notifications@github.com<mailto:notifications@github.com>> wrote:

They may also help users when they’re paging through result pages. If we have checkboxes so users can select sets of result items *across* search result pages, that perhaps might reduce this type of usage.

**Comment by aw-bib** [comment]
Would it probably be sensible to give the recid in front instead of a counter or even better a unique, persistent accession number? Also addressing the ticket-issue @bing13 mentioned?

BTW: If you're not in the know, it is not that easy on inspire to know what to give as a reference for a paper in a ticket (most likely I'd resort to the bibliographic blurb). For many web pages, even today, the URL is entirely useless as it is just gets invalid, an also most browsers do fancy things with the former url bar, so people are not that aware of it anymore, either. So for the non-techie... On join2 we use a "Request correction" link in `HD` that constructs a useful message. This solves most of our problems here, until people start deleting all the pre-formulated text and subject. Besides we have a a definite accession number printed in bold on top. (Something I'd strongly suggest for inspire.)

**Comment by bing13** [comment]
From a UX perspective, sequential index numbers also provide an indication of "how far" into a search result list you are, as you traverse back and forth.  It's a useful signpost in that sense.

**Comment by jmartinm** [comment]
In the past I also got feedback from our AB member John that sometimes he uses the number, for example when chatting with someone (on the phone or chatting) in order to reference a record. Like `look at record 3 on this search` so might be useful for more people.

**Comment by kaplun** [comment]
:+1: for sequential IDs related to search results, indeed.
:-1: to record IDs (imagine on the phone: "do you see record one million seven hundred thousands and five? The one after half a million and seven hundred and forty five).

**Comment by salmele** [comment]
John's point is valid... as long as folks talking to each others have different results on their screens anyhow. While we won't be having a 'bubble' around each searcher, it is true that just the way facets would be (de-)selected in bringing someone to a give screen might make this point harder to be applied...

**Comment by kaplun** [comment]
What is the exact status of this Issue? @jmartinm, @ioannistsanaktsidis ?

**Comment by ioannistsanaktsidis** [comment]
```
 Add number and checkbox in front of every result ?
```
The checkbox is added, the number not. 

```
PDF Download - single button when only one available and dropdown menu when different versions available.
```
This one is missing.

**Comment by jmartinm** [comment]
The only pending task has been separated into a different `issue` - https://github.com/inspirehep/inspire-next/issues/1058
