### ISSUE TITLE
Finalize prod to labs synchronization

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#408]
- [x] Regenerate Demosite with all links (see #357)
- [x] Generate full dump of INSPIRE using enhanced MARCXML
- [x] Investigate whether we can have publish/subscribe via Redis between Prod and Labs
- [x] Alternatively implement POST handler on Labs to receive enhanced MARCXML
- [x] New bibtasklet to continously push either via POST request or via Redis pub/sub modified records (e.g. due to a new citation or a new claim)
- [x] New `inspire_prod_records` model to store intermediate MARCXML (see below)
- [x] Mini Celery task that perform dojson/creation/indexing. In case of failure flag this in `inspire_prod_records` (@jmartinm)
- [x] Celery beat task that reads from file above Redis, store into `inspire_prod_records` and call mini celery task (using `BLPOP`)
- [x] `inveniomanage` command to replay flagged records in `inspire_prod_records`
- [x] improve `dojson` not to read everything into memory. (available in dojson 0.4.0)
- [x] `inveniomanage` command to read from disk rather than Redis and scedule Mini Celery tasks.
- [x] Test and perform initial of Prod into Labs

---

`inspire_prod_records` model:

column | type | description
-----------|-------|-----------------
recid | int | ID of corresponding record
last_update | datetime | last time it was updated
marcxml | blob | the actual compressed blob
successful | bool | False if dojson failed, NULL if it was never processed

**Comment by kaplun** [comment]
@jalavik @jmartinm I have updated this task according to today musings

**Comment by kaplun** [comment]
See: inspirehep/inspire#122.

Currently a full dump with enhanced marcxml is being generated under `/nfs/production/var/tmp-shared/prodsync.xml`.

Once labs side is ready, we can then switch to use redis. The Labs client should simply connect to a shared redis instance (between prod and labs) and issue a blocking pop statement on a given `records` key.

**Comment by kaplun** [comment]
See: invenio.qa.cfg

**Comment by kaplun** [comment]
Getting there!

**Comment by kaplun** [comment]
For reference see: #596 #580 #570 #557 #550 #536

**Comment by kaplun** [comment]
Now that continuos migration is basically running on QA, I am closing this ticket.
