### ISSUE TITLE
Faceting of records in Literature

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#411]
Facets (now called aggregations in ElasticSearch) need to be implemented and the following facets need to be present in the Literature collection:

*  [x] Subject (field 65017 with subfield 2 == INSPIRE)
* [x] Document type (subset of 980__a): It also needs to be made more human readable, e.g `Conference Paper` instead of `ConferencePaper`
* [x] Author
* [x] Year
* [x] Experiment (field 693__e)

After merging https://github.com/inspirehep/inspire-next/issues/426 basic faceting is available. Things to address:

* [x] Order facets. Currently the order the aggregations are defined in `search.py` does not reflect the UI. In the template the aggregations are iterated blindly and displayed. One option is in our INSPIRE template to not iterate over them but for each Facet just access directly its content.
* [x] BUG: Fix infinite &p addition to URL while changing facets
* [ ] BUG: In the Author facet. The first result shows 12 matches but when clicked 11 results are displayed.
* [x] BUG?: In the demo site with 200 records, clicking on a facet has a slow response. Time seems to be spend in the JavaScript code as the server does not show `GET /search?post_filter` while waiting.
* [x] We need postprocessing of the aggregations for certain cases like `date-by-year` aggregation. Results are returned in `epoch` format and need to converted to human readable year. Also for document types we can introduce a mapping between collection names and human readable document types. We can either do this in JavaScript or do it in the backend like [hepdata](https://github.com/HEPData/hepdata/blob/master/hepdata/ext/elasticsearch/aggregations.py#L29)
* [x] Selecting a given facet should refresh the whole page and facets should be regenerated so that counts reflect the current user query AND the selected facets.
* [x] All unnecessary JavaScript should be removed from the page (like legacy facets JavaScript)
* [x] Design can be refined and the title of each facet should be `Filter by Author`, `Filter by Document type`
* [ ] As an extra we should add the widget to show the currently selected filters and a Clear Filters button.
![screen shot 2015-10-30 at 10 25 24 am](https://cloud.githubusercontent.com/assets/580727/10842243/9b93d888-7ef0-11e5-97c6-1f0882ba287e.png)

NOTE: There is the following Invenio related ticket https://github.com/inveniosoftware/invenio/issues/3415 that does not seem active at the moment.

**Comment by kaplun** [comment]
How these facets have been chosen?

**Comment by jmartinm** [comment]
Depends on https://github.com/inspirehep/inspire-next/issues/426

> How these facets have been chosen?

So far from the recommendation of @inspire-data 

Once we make this work we will ask some users for their opinion.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm  I started playing a little bit with facets. The ordering of facets is now done in our search.html, so we can take care as we want. So this problem is solved. The url addition bug is solved. I added a regex so as to filter the empty parameteres in a url. Finally I also fixed the year problem by creating a jinja filter and also changing it in the ES so as not  to crash while you filter by year. Cheers :dancer:

**Comment by ioannistsanaktsidis** [comment]
Concerning the slow response of GET /search?post_filter  , I debugged it yesterday. The problem seems to be here return response_formated_records(response.records(), of, **ctx) . When I remove the filtered_facets from the ctx, it seems to be quite faster.

**Comment by ioannistsanaktsidis** [comment]
Also concerning the unused Javascript, there is a file called facet.js . I think this one is unused and can be removed.
