### ISSUE TITLE
dojson: support for enhanced MARCXML links

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#485]
https://github.com/inspirehep/inspire/commit/de148e839653c18ad0c6572874ffe85702509482 and followed up commits have introduced several links across records.
```    
         100/700 $x with Record ID of linked HepName,
                 $y with True/False if the signature is claimed
                 $z with Record ID of institution
         371/110 $z with Record ID of institution
         502     $z with Record ID of institution
         999C5   $0 with on the fly discovered Record IDs (not for books)
         773     $0 with Record ID of corresponding Book or Proceeding
                 $1 with Record ID of corresponding Journal
                 $2 with Record ID of corresponding Conference
         693/710 $0 with Record ID of corresponding experiment
```

Dojson scripts should amended accordingly to translate this links from MARCXML into JSON.
* [x] `100/700 $x` in HEP should go to `authors[].recid`
* [x] `100/700 $y` in HEP should go to `authors[].curated_relation` (in `dojson` this is currently called `claimed`)
* [x] `100/700 $z` in HEP should go to `authors[].affiliations[].recid` (`curated_relation` is set to `true` if there is a recid.
* [x] `502 $z` in HEP should go to `thesis[].recid` (`curated` blablabla)
* [x] `371 $z` in HepNames should go to `positions[].institution.recid` (`curated_relation to `true`)
* [x] `110 $z` in Jobs should go to `institution.recid` (`curated_relation to `true`)
* [x] `999C5  $0` in HEP should go into `references[].recid`
* [x] `773 $0` in HEP should go into into new `book.recid` field if `BOOKCHAPTER`
* [x] `773 $1` in HEP should go into `publication_info.journal_recid` (which should be added to `hep-0.0.1.json`
* [x] `773 $2` in HEP should go into `publication_info.recid`
* [x] `693 $0`in HEP should go to `accelerator_experiment.recid` (`curated_relation` set to `true`)
* [x] `710 $0`in HEP should go to `collaboration.recid` (does not exist yet.)

**Comment by kaplun** [comment]
cc: @jmartinm

**Comment by kaplun** [comment]
I think this still missing. @ioannistsanaktsidis can you take care of this? In particular the links in the HEP records are necessary for the milestone.

**Comment by ioannistsanaktsidis** [comment]
Yes no worries, I will take a look.

**Comment by ioannistsanaktsidis** [comment]
```
*  773 $0 in HEP should go into into new book.recid field if BOOKCHAPTER
*  710 $0 in HEP should go to collaboration.recid (does not exist yet.)
```
@kaplun for these 2 I have some questions. For the first one I am not sure I am following. Should I check bookchapter from that field I guess facet_inspire_doc_type?It is the one generated here https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/receivers.py . For the second I guess we can not add it yet as it is missing from the marc right? Cheers!

**Comment by kaplun** [comment]
> *  `773 $0 in HEP should go into into new book.recid field if BOOKCHAPTER`
> *  `710 $0 in HEP should go to collaboration.recid (does not exist yet.)`

> @kaplun for these 2 I have some questions. For the first one I am not sure I am following. Should I check bookchapter from that field I guess facet_inspire_doc_type?It is the one generated here https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/receivers.py . For the second I guess we can not add it yet as it is missing from the marc right? Cheers!

@ioannistsanaktsidis sorry seeing this only now. Indeed I discussed with @annetteholtkamp and you can ignore 710__0. For 773__0 indeed if the current document is of type bookchapter, then you populate book.recid.
