### ISSUE TITLE
Set up analyzers

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#685]
* [ ] Take into consideration LaTeX formulas. Titles and abstract can contain LaTeX formulas that should not be broken by the tokenizer so that they are searchable. A [custom analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/analysis-custom-analyzer.html) could be used.

* [ ] Experiment. Have an analyzed a non-analyzed version to match `CERN-LHC-LHCb` even when the user has typed `LHCb`.

* [ ] We have to make sure, at record creation/modification, that the DOI is normalized e.g. to 10.xxx/xxx, without any superflous prefix, and that the search term is receiving the same treatment. Alternatively we need, for every DOI to index it also with doi: and http://dx.doi.org/ prefixes. This seems something that could be made easily with a [Groovy script](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html). Or altenatively with one more pythonic enhancer.

* [ ] arXiv eprints. Same as with DOIs they need to be found with and without prefix.

* [ ] isbns Keep raw and analyzed version to find them with and without dashes.

**Comment by jmartinm** [comment]
Tasks extracted from https://github.com/inspirehep/inspire-next/pull/641

**Comment by kaplun** [comment]
> This seems something that could be made easily with a Groovy script. Or altenatively with one more pythonic enhancer.

When possible, :+1: to indeed use index-time expansions + serch-time normalization based on Groovy!

**Comment by kaplun** [comment]
> Expand title, abstract and keywords with synonyms.
@fschwenn the `HEP.rdf` ontology is still maintained at DESY, correct? Do you think it can be used as a basis for building a synonyms table? (i.e. simple string mapping useful for indexing/searching a given word as two words).

**Comment by fschwenn** [comment]
Yes, the ontology is still maintained at DESY. It contains informations on synonyms in the sense that if altLabel is found, prefLabel is assigned. But one can not use it without proof reading, e.g. 
<prefLabel xml:lang="en">string: Green-Schwarz</prefLabel> 
<altLabel xml:lang="en">Green-Schwarz action</altLabel> 
<altLabel xml:lang="en">Green-Schwarz superstring</altLabel> 

If "Green-Schwarz action" is found in the text, we assign "string: Green-Schwarz". However, they are not really synonyms. 

-- 
Florian Schwennsen 
Deutsches Elektronen-Synchrotron DESY 
Building 01 Room O1.446 
phone: +49-40-8998-6190

**Comment by kaplun** [comment]
> Yes, the ontology is still maintained at DESY. It contains informations on synonyms in the sense that if altLabel is found, prefLabel is assigned. But one can not use it without proof reading.

I see... @inspirehep/inspire-dir do you have maybe a good idea were we could obtain a HEP synonym list? E.g. to be able to search for β and beta, for "HEP" and for "High Energy Physics", and of course much more sensible substitutions...

**Comment by jmartinm** [comment]
Not sure if this can be helpful :) http://www.personal.kent.edu/~plucasst/HEPThesaurus/Alphabetical%20Thesaurus.htm

**Comment by ksachs** [comment]
I think SPIRES had a list at least for the most common abreviations. E.g. title-variant supersymmetry got automatically assigned to articles with title SUSY.

**Comment by kaplun** [comment]
@jacquerie wanted to attack mappings at some point so I am assigning to him so that we are sure not to forget the points listed here.

**Comment by kaplun** [comment]
WRT LaTeX see also #1165

**Comment by jmartinm** [comment]
@StellaCh this should be reviewed by the person implementing the search since it seems still relevant.

**Comment by chris-asl** [comment]
@jmartinm regarding DOI and arXiv eprints, what could the superflous prefix be? 
Something like `arxiv:ARXIV_ID`?
And for DOIs?

**Comment by jmartinm** [comment]
> @jmartinm regarding DOI and arXiv eprints, what could the superflous prefix be?
Something like arxiv:ARXIV_ID?
And for DOIs?

Ideally you can check the search logs for examples. For arxiv the prefix that some people might use is `arxiv:` and for DOI it could be `doi:` or ` http://dx.doi.org/` @annetteholtkamp or @michamos can confirm if they know other prefixes that should work when searching

**Comment by michamos** [comment]
@chris-asl for arXiv we have https://github.com/inspirehep/inspire-schemas/blob/ac809becb858cfe2a1c695c18f00014109138dca/inspire_schemas/builders/references.py#L110-L126. You can move it to `inspire_schemas.utils` if it's needed for search too.
For dois, you could use directly `idutils.normalize_doi`.
