### ISSUE TITLE
Enhanced MARCXML links part 2

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#721]
We should add support for
* `701__z` for record ID of institution of supervisor
* `773__0` with Record ID of corresponding Report (as coming from $r)
* While there: populate outgoing 961__c with: creation date, to be stored into the create metadata field.

* [x] Amend legacy to export these fields
* [x] Recreate demo records
* [x] Recreate dump
* [x] Amend dojson to support these fields @ioannistsanaktsidis

**Comment by kaplun** [comment]
cc @jmartinm

**Comment by kaplun** [comment]
Dump is being recreated at the moment, and will be available by tomorrow evening.

**Comment by jmartinm** [comment]
> Dump is being recreated at the moment, and will be available by tomorrow evening.

Shall we update the demo records so that @ioannistsanaktsidis can complete the `dojson` part by tomorrow?

**Comment by kaplun** [comment]
Yep I am doing that now

**Comment by kaplun** [comment]
Here it is coming #725

**Comment by jmartinm** [comment]
This is already done.
