### ISSUE TITLE
ORCID Integration

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#915]
* [ ] Require token that allows editing of ORCID profile
* [ ] Upon first ORCID login, use ORCID info to propose suitable un-assigned author profile
  * [ ] Profile suggestion algorithm
  * [ ] New profile generation algorithm
* [ ] When record is modified, push to ORCID the modified record for all the claimed signatures linked to an ORCID profile for which we have authorization (through signal `after_record_update`, `after_record_create`). (rate_limited `celery` task)
   * [ ] HEP record to ORCID format conversion
   * [ ] Data record to ORCID format conversion
* [ ] Regular heartbeat `celery` task that pull ORCID information for every ORCID to perform autoclaim
   * [ ] `autoclaim` algorithm that, given a HEP record and a profile is able to recognize which signature has to point to the given profile.

**Comment by kaplun** [comment]
For the required token see: https://github.com/inspirehep/inspire-next/pull/1039#issuecomment-212433190

**Comment by kaplun** [comment]
@Panos512 can you update this issue with pointers with the several PRs and what is being completed?

**Comment by Panos512** [comment]
Profile suggestion algorithm -> #1318 
HEP record to ORCID format conversion -> #1093

**Comment by kaplun** [comment]
@StellaCh this is a plan of what is needed for ORCID. Where would you want it?
