### ISSUE TITLE
SCOAP³ integration

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#916]
INSPIRE should aggregate as much info as possible from SCOAP³.

* [ ] Consider http://repo.scoap3.org/ as yet another publisher.
  * [ ] Match harvested record against INSPIRE to see if record is duplicate or not
* [ ] If record already exist in INSPIRE merge information
  * [ ] align author list and when possible integrate affiliations and ORCIDs
  * [ ] fetch fulltext

**Comment by annetteholtkamp** [comment]
Just to be clear: You talk only about updating records with info from scoap3 and don't foresee to add new records, right? Because that would complicate life for us. The records we get from publishers are probably more complete (references etc) and run through dedicated conversion scripts. Merging publisher records is much more difficult than adding new ones.
The only relevant info from scoap3 are probably the Orcid's. For the full texts there exists already a push by Wojtek. Does that need to be redone?

- Annette

On Feb 25, 2016, at 2:32 PM, Samuele Kaplun <notifications@github.com<mailto:notifications@github.com>> wrote:


INSPIRE should aggregate as much info as possible from SCOAP³.

  *    Consider http://repo.scoap3.org/ as yet another publisher.
     *    Match harvested record against INSPIRE to see if record is duplicate or not
  *    If record already exist in INSPIRE merge information
     *    align author list and when possible integrate affiliations and ORCIDs
     *    fetch fulltext

**Comment by kaplun** [comment]
> Just to be clear: You talk only about updating records with info from scoap3 and don't foresee to add new records, right? 

Is this valid for all the 10 SCOAP³ journals? (i.e. are we receiving feeds from them already?)

> Because that would complicate life for us. The records we get from publishers are probably more complete (references etc) and run through dedicated conversion scripts. Merging publisher records is much more difficult than adding new ones.

Ideally we should make the automatic merging of records the norm, once we learn how to properly merge authorlists, reference lists etc. Then the SCOAP³ merging could be only one of the many sources.

> The only relevant info from scoap3 are probably the Orcid's. For the full texts there exists already a push by Wojtek. Does that need to be redone?

Yep. Everything needs to be redone (the day Labs become the master of the records). So far copying the fulltext from SCOAP³ is done with a small bibtasklet on legacy.
