### ISSUE TITLE
Porting testsuite

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#918]
All the tests in `master` branch should be ported and pass on Travis.

* [x] test_author_bibfield.py
* [ ] test_author_workflow.py
* [ ] test_authors.py
* [x] test_bai.py (#1088)
* [x] test_bibfield.py
* [x] test_bibtex.py (#1024)
* [ ] test_cache_manager.py
* [x] test_citation_counts.py (#1036)
* [x] test_cvlatex.py (#1024)
* [x] test_cvlatex_html_text.py (#1024)
* [x] test_date_utils.py
* [x] test_datefilter.py
* [x] test_dojson_receivers.py (#1088)
* [x] test_export.py (#1024)
* [ ] test_formulas.py (depends on #1165)
* [x] test_hep.py
* [ ] test_hep_submission.py
* [x] test_hepnames.py
* [ ] test_holdingpen.py
* [x] test_icu.py (#1088)
* [ ] test_indexing.py
* [x] test_latex.py (#1024)
* [ ] test_matching.py
* [ ] test_migrator_utils.py
* [ ] ~~test_publication_info.py~~ (Done in #967 with what I think is a better approach)
* [ ] test_records.py
* [ ] test_reindexing.py
* [x] test_robotupload.py
* [x] test_text.py
* [ ] ~~test_utils.py~~ (IMO test belongs [here](https://github.com/inspirehep/invenio-utils/pull/2))
* [ ] ~~test_version.py~~ (Logic to be tested is no longer there, and isn't worth the effort to port)
* [x] test_views.py
* [ ] test_workflows.py

**Comment by jacquerie** [comment]
You can assign this to me, so (I think) I can start ticking off boxes : )

**Comment by kaplun** [comment]
@jacquerie are there one or more PR associated with this issue?

**Comment by jacquerie** [comment]
Definitely #1024 and #1036, but probably more. I haven't been very diligent in ticking off boxes : /

**Comment by kaplun** [comment]
D'oh! Can you refer to this issue then in the commit log of the respective PRs?

**Comment by jmartinm** [comment]
I think this issue is not relevant any more. Tests have been ported as needed and new ones have been created. @jacquerie can you confirm and close?
